using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Discord;
using Discord.WebSocket;

namespace ForumCrawler
{
    class QuickChatWatcher
    {
        // Keep list as simple as possible, do not add duplicate messages: "Thanks!" is not allowed, because "Thank you." already exists.
        private static readonly string[] ValidQuickChats =
        {
            // EE
            "Hi.", 
            "Goodbye.", 
            "Help me!", 
            "Thank you.", 
            "Follow me.", 
            "Stop!", 
            "Yes.", 
            "No.", 
            "Right.", 
            "Left.",

            // Color
            "White.",
            "Grey.",
            "Black.",
            "Red.",
            "Orange.",
            "Yellow.",
            "Green.",
            "Cyan.",
            "Blue.",
            "Purple.",

            // Country
            "Grinning.",
            "Smiley.",
            "Smile.",
            "Grin.",
            "Laughing.",
            "Satisfied.",
            "Sweat smile.",
            "Joy.",
            "Rofl.",
            "Rolling on the floor laughing.",
            "Relaxed.",
            "Blush.",
            "Innocent.",
            "Slight smile.",
            "Slightly smiling face.",
            "Upside down.",
            "Upside down face.",
            "Wink.",
            "Relieved.",
            "Heart eyes.",
            "Smiling face with 3 hearts.",
            "Kissing heart.",
            "Kissing.",
            "Kissing smiling eyes.",
            "Kissing closed eyes.",
            "Yum.",
            "Stuck out tongue.",
            "Stuck out tongue closed eyes.",
            "Stuck out tongue winking eye.",
            "Zany face.",
            "Face with raised eyebrow.",
            "Face with monocle.",
            "Nerd.",
            "Nerd face.",
            "Sunglasses.",
            "Star struck.",
            "Partying face.",
            "Smirk.",
            "Unamused.",
            "Disappointed.",
            "Pensive.",
            "Worried.",
            "Confused.",
            "Slight frown.",
            "Slightly frowning face.",
            "Frowning2.",
            "White frowning face.",
            "Persevere.",
            "Confounded.",
            "Tired face.",
            "Weary.",
            "Pleading face.",
            "Cry.",
            "Sob.",
            "Triumph.",
            "Angry.",
            "Rage.",
            "Face with symbols over mouth.",
            "Exploding head.",
            "Flushed.",
            "Hot face.",
            "Cold face.",
            "Scream.",
            "Fearful.",
            "Cold sweat.",
            "Disappointed relieved.",
            "Sweat.",
            "Hugging.",
            "Hugging face.",
            "Thinking.",
            "Thinking face.",
            "Face with hand over mouth.",
            "Yawning face.",
            "Shushing face.",
            "Lying face.",
            "Liar.",
            "No mouth.",
            "Neutral face.",
            "Expressionless.",
            "Grimacing.",
            "Rolling eyes.",
            "Face with rolling eyes.",
            "Hushed.",
            "Frowning.",
            "Anguished.",
            "Open mouth.",
            "Astonished.",
            "Sleeping.",
            "Drooling face.",
            "Drool.",
            "Sleepy.",
            "Dizzy face.",
            "Zipper mouth.",
            "Zipper mouth face.",
            "Woozy face.",
            "Nauseated face.",
            "Sick.",
            "Face vomiting.",
            "Sneezing face.",
            "Sneeze.",
            "Mask.",
            "Thermometer face.",
            "Face with thermometer.",
            "Head bandage.",
            "Face with head bandage.",
            "Money mouth.",
            "Money mouth face.",
            "Cowboy.",
            "Face with cowboy hat.",
            "Smiling imp.",
            "Imp.",
            "Japanese ogre.",
            "Japanese goblin.",
            "Clown.",
            "Clown face.",
            "Poop.",
            "Shit.",
            "Hankey.",
            "Poo.",
            "Ghost.",
            "Skull.",
            "Skeleton.",
            "Skull crossbones.",
            "Skull and crossbones.",
            "Alien.",
            "Space invader.",
            "Robot.",
            "Robot face.",
            "Jack o lantern.",
            "Smiley cat.",
            "Smile cat.",
            "Joy cat.",
            "Heart eyes cat.",
            "Smirk cat.",
            "Kissing cat.",
            "Scream cat.",
            "Crying cat face.",
            "Pouting cat.",
            "Palms up together.",
            "Open hands.",
            "Raised hands.",
            "Clap.",
            "Handshake.",
            "Shaking hands.",
            "Thumbsup.",
            "+1.",
            "Thumbup.",
            "Thumbsdown.",
            "-1.",
            "Thumbdown.",
            "Punch.",
            "Fist.",
            "Left facing fist.",
            "Left fist.",
            "Right facing fist.",
            "Right fist.",
            "Fingers crossed.",
            "Hand with index and middle finger crossed.",
            "V.",
            "Love you gesture.",
            "Metal.",
            "Sign of the horns.",
            "Ok hand.",
            "Pinching hand.",
            "Point left.",
            "Point right.",
            "Point up 2.",
            "Point down.",
            "Point up.",
            "Raised hand.",
            "Raised back of hand.",
            "Back of hand.",
            "Hand splayed.",
            "Raised hand with fingers splayed.",
            "Vulcan.",
            "Raised hand with part between middle and ring fingers.",
            "Wave.",
            "Call me.",
            "Call me hand.",
            "Muscle.",
            "Mechanical arm.",
            "Middle finger.",
            "Reversed hand with middle finger extended.",
            "Writing hand.",
            "Pray.",
            "Foot.",
            "Leg.",
            "Mechanical leg.",
            "Lipstick.",
            "Kiss.",
            "Lips.",
            "Tooth.",
            "Bone.",
            "Tongue.",
            "Ear.",
            "Ear with hearing aid.",
            "Nose.",
            "Footprints.",
            "Eye.",
            "Eyes.",
            "Brain.",
            "Speaking head.",
            "Speaking head in silhouette.",
            "Bust in silhouette.",
            "Busts in silhouette.",
            "Baby.",
            "Girl.",
            "Child.",
            "Boy.",
            "Woman.",
            "Adult.",
            "Man.",
            "Woman curly haired.",
            "Man curly haired.",
            "Woman red haired.",
            "Man red haired.",
            "Blond haired woman.",
            "Blond haired person.",
            "Person with blond hair.",
            "Blond haired man.",
            "Woman white haired.",
            "Man white haired.",
            "Woman bald.",
            "Man bald.",
            "Bearded person.",
            "Older woman.",
            "Grandma.",
            "Older adult.",
            "Older man.",
            "Man with chinese cap.",
            "Man with gua pi mao.",
            "Person wearing turban.",
            "Man with turban.",
            "Woman wearing turban.",
            "Man wearing turban.",
            "Woman with headscarf.",
            "Police officer.",
            "Cop.",
            "Woman police officer.",
            "Man police officer.",
            "Construction worker.",
            "Woman construction worker.",
            "Man construction worker.",
            "Guard.",
            "Guardsman.",
            "Woman guard.",
            "Man guard.",
            "Detective.",
            "Spy.",
            "Sleuth or spy.",
            "Woman detective.",
            "Man detective.",
            "Woman health worker.",
            "Man health worker.",
            "Woman farmer.",
            "Man farmer.",
            "Woman cook.",
            "Man cook.",
            "Woman student.",
            "Man student.",
            "Woman singer.",
            "Man singer.",
            "Woman teacher.",
            "Man teacher.",
            "Woman factory worker.",
            "Man factory worker.",
            "Woman technologist.",
            "Man technologist.",
            "Woman office worker.",
            "Man office worker.",
            "Woman mechanic.",
            "Man mechanic.",
            "Woman scientist.",
            "Man scientist.",
            "Woman artist.",
            "Man artist.",
            "Woman firefighter.",
            "Man firefighter.",
            "Woman pilot.",
            "Man pilot.",
            "Woman astronaut.",
            "Man astronaut.",
            "Woman judge.",
            "Man judge.",
            "Bride with veil.",
            "Man in tuxedo.",
            "Princess.",
            "Prince.",
            "Superhero.",
            "Woman superhero.",
            "Man superhero.",
            "Supervillain.",
            "Woman supervillain.",
            "Man supervillain.",
            "Mrs claus.",
            "Mother christmas.",
            "Santa.",
            "Mage.",
            "Woman mage.",
            "Man mage.",
            "Elf.",
            "Woman elf.",
            "Man elf.",
            "Vampire.",
            "Woman vampire.",
            "Man vampire.",
            "Zombie.",
            "Woman zombie.",
            "Man zombie.",
            "Genie.",
            "Woman genie.",
            "Man genie.",
            "Merperson.",
            "Mermaid.",
            "Merman.",
            "Fairy.",
            "Woman fairy.",
            "Man fairy.",
            "Angel.",
            "Pregnant woman.",
            "Expecting woman.",
            "Breast feeding.",
            "Person bowing.",
            "Bow.",
            "Woman bowing.",
            "Man bowing.",
            "Person tipping hand.",
            "Information desk person.",
            "Woman tipping hand.",
            "Man tipping hand.",
            "Person gesturing no.",
            "No good.",
            "Woman gesturing no.",
            "Man gesturing no.",
            "Person gesturing ok.",
            "Ok woman.",
            "Woman gesturing ok.",
            "Man gesturing ok.",
            "Person raising hand.",
            "Raising hand.",
            "Woman raising hand.",
            "Man raising hand.",
            "Deaf person.",
            "Deaf woman.",
            "Deaf man.",
            "Person facepalming.",
            "Face palm.",
            "Facepalm.",
            "Woman facepalming.",
            "Man facepalming.",
            "Person shrugging.",
            "Shrug.",
            "Woman shrugging.",
            "Man shrugging.",
            "Person pouting.",
            "Person with pouting face.",
            "Woman pouting.",
            "Man pouting.",
            "Person frowning.",
            "Woman frowning.",
            "Man frowning.",
            "Person getting haircut.",
            "Haircut.",
            "Woman getting haircut.",
            "Man getting haircut.",
            "Person getting massage.",
            "Massage.",
            "Woman getting face massage.",
            "Man getting face massage.",
            "Person in steamy room.",
            "Woman in steamy room.",
            "Man in steamy room.",
            "Nail care.",
            "Selfie.",
            "Dancer.",
            "Man dancing.",
            "Male dancer.",
            "People with bunny ears partying.",
            "Dancers.",
            "Women with bunny ears partying.",
            "Men with bunny ears partying.",
            "Levitate.",
            "Man in business suit levitating.",
            "Person walking.",
            "Walking.",
            "Woman walking.",
            "Man walking.",
            "Person running.",
            "Runner.",
            "Woman running.",
            "Man running.",
            "Person standing.",
            "Woman standing.",
            "Man standing.",
            "Person kneeling.",
            "Woman kneeling.",
            "Man kneeling.",
            "Woman with probing cane.",
            "Man with probing cane.",
            "Woman in motorized wheelchair.",
            "Man in motorized wheelchair.",
            "Woman in manual wheelchair.",
            "Man in manual wheelchair.",
            "People holding hands.",
            "Couple.",
            "Two women holding hands.",
            "Two men holding hands.",
            "Couple with heart.",
            "Couple with heart woman man.",
            "Couple ww.",
            "Couple with heart ww.",
            "Couple mm.",
            "Couple with heart mm.",
            "Couplekiss.",
            "Kiss woman man.",
            "Kiss ww.",
            "Couplekiss ww.",
            "Kiss mm.",
            "Couplekiss mm.",
            "Family.",
            "Family man woman boy.",
            "Family mwg.",
            "Family mwgb.",
            "Family mwbb.",
            "Family mwgg.",
            "Family wwb.",
            "Family wwg.",
            "Family wwgb.",
            "Family wwbb.",
            "Family wwgg.",
            "Family mmb.",
            "Family mmg.",
            "Family mmgb.",
            "Family mmbb.",
            "Family mmgg.",
            "Family woman boy.",
            "Family woman girl.",
            "Family woman girl boy.",
            "Family woman boy boy.",
            "Family woman girl girl.",
            "Family man boy.",
            "Family man girl.",
            "Family man girl boy.",
            "Family man boy boy.",
            "Family man girl girl.",
            "Yarn.",
            "Thread.",
            "Coat.",
            "Lab coat.",
            "Safety vest.",
            "Womans clothes.",
            "Shirt.",
            "Jeans.",
            "Shorts.",
            "Necktie.",
            "Dress.",
            "Bikini.",
            "One piece swimsuit.",
            "Kimono.",
            "Sari.",
            "Womans flat shoe.",
            "High heel.",
            "Sandal.",
            "Boot.",
            "Ballet shoes.",
            "Mans shoe.",
            "Athletic shoe.",
            "Hiking boot.",
            "Briefs.",
            "Socks.",
            "Gloves.",
            "Scarf.",
            "Tophat.",
            "Billed cap.",
            "Womans hat.",
            "Mortar board.",
            "Helmet with cross.",
            "Helmet with white cross.",
            "Crown.",
            "Ring.",
            "Pouch.",
            "Purse.",
            "Handbag.",
            "Briefcase.",
            "School satchel.",
            "Luggage.",
            "Eyeglasses.",
            "Dark sunglasses.",
            "Goggles.",
            "Diving mask.",
            "Closed umbrella.",
            "Dog.",
            "Cat.",
            "Mouse.",
            "Hamster.",
            "Rabbit.",
            "Fox.",
            "Fox face.",
            "Bear.",
            "Panda face.",
            "Koala.",
            "Tiger.",
            "Lion face.",
            "Lion.",
            "Cow.",
            "Pig.",
            "Pig nose.",
            "Frog.",
            "Monkey face.",
            "See no evil.",
            "Hear no evil.",
            "Speak no evil.",
            "Monkey.",
            "Chicken.",
            "Penguin.",
            "Bird.",
            "Baby chick.",
            "Hatching chick.",
            "Hatched chick.",
            "Duck.",
            "Eagle.",
            "Owl.",
            "Bat.",
            "Wolf.",
            "Boar.",
            "Horse.",
            "Unicorn.",
            "Unicorn face.",
            "Bee.",
            "Bug.",
            "Butterfly.",
            "Snail.",
            "Shell.",
            "Beetle.",
            "Ant.",
            "Mosquito.",
            "Cricket.",
            "Spider.",
            "Spider web.",
            "Scorpion.",
            "Turtle.",
            "Snake.",
            "Lizard.",
            "T rex.",
            "Sauropod.",
            "Octopus.",
            "Squid.",
            "Shrimp.",
            "Lobster.",
            "Oyster.",
            "Crab.",
            "Blowfish.",
            "Tropical fish.",
            "Fish.",
            "Dolphin.",
            "Whale.",
            "Whale2.",
            "Shark.",
            "Crocodile.",
            "Tiger2.",
            "Leopard.",
            "Zebra.",
            "Gorilla.",
            "Orangutan.",
            "Elephant.",
            "Hippopotamus.",
            "Rhino.",
            "Rhinoceros.",
            "Dromedary camel.",
            "Camel.",
            "Giraffe.",
            "Kangaroo.",
            "Water buffalo.",
            "Ox.",
            "Cow2.",
            "Racehorse.",
            "Pig2.",
            "Ram.",
            "Llama.",
            "Sheep.",
            "Goat.",
            "Deer.",
            "Dog2.",
            "Guide dog.",
            "Service dog.",
            "Poodle.",
            "Cat2.",
            "Rooster.",
            "Turkey.",
            "Peacock.",
            "Parrot.",
            "Swan.",
            "Flamingo.",
            "Dove.",
            "Dove of peace.",
            "Rabbit2.",
            "Sloth.",
            "Otter.",
            "Skunk.",
            "Raccoon.",
            "Badger.",
            "Mouse2.",
            "Rat.",
            "Chipmunk.",
            "Hedgehog.",
            "Feet.",
            "Paw prints.",
            "Dragon.",
            "Dragon face.",
            "Cactus.",
            "Christmas tree.",
            "Evergreen tree.",
            "Deciduous tree.",
            "Palm tree.",
            "Seedling.",
            "Herb.",
            "Shamrock.",
            "Four leaf clover.",
            "Bamboo.",
            "Tanabata tree.",
            "Leaves.",
            "Fallen leaf.",
            "Maple leaf.",
            "Mushroom.",
            "Ear of rice.",
            "Bouquet.",
            "Tulip.",
            "Rose.",
            "Wilted rose.",
            "Wilted flower.",
            "Hibiscus.",
            "Cherry blossom.",
            "Blossom.",
            "Sunflower.",
            "Sun with face.",
            "Full moon with face.",
            "First quarter moon with face.",
            "Last quarter moon with face.",
            "New moon with face.",
            "Full moon.",
            "Waning gibbous moon.",
            "Last quarter moon.",
            "Waning crescent moon.",
            "New moon.",
            "Waxing crescent moon.",
            "First quarter moon.",
            "Waxing gibbous moon.",
            "Crescent moon.",
            "Earth americas.",
            "Earth africa.",
            "Earth asia.",
            "Ringed planet.",
            "Dizzy.",
            "Star.",
            "Star2.",
            "Sparkles.",
            "Zap.",
            "Comet.",
            "Boom.",
            "Fire.",
            "Flame.",
            "Cloud tornado.",
            "Cloud with tornado.",
            "Rainbow.",
            "Sunny.",
            "White sun small cloud.",
            "White sun with small cloud.",
            "Partly sunny.",
            "White sun cloud.",
            "White sun behind cloud.",
            "Cloud.",
            "White sun rain cloud.",
            "White sun behind cloud with rain.",
            "Cloud rain.",
            "Cloud with rain.",
            "Thunder cloud rain.",
            "Thunder cloud and rain.",
            "Cloud lightning.",
            "Cloud with lightning.",
            "Cloud snow.",
            "Cloud with snow.",
            "Snowflake.",
            "Snowman2.",
            "Snowman.",
            "Wind blowing face.",
            "Dash.",
            "Droplet.",
            "Sweat drops.",
            "Umbrella.",
            "Umbrella2.",
            "Ocean.",
            "Fog.",
            "Green apple.",
            "Apple.",
            "Pear.",
            "Tangerine.",
            "Lemon.",
            "Banana.",
            "Watermelon.",
            "Grapes.",
            "Strawberry.",
            "Melon.",
            "Cherries.",
            "Peach.",
            "Mango.",
            "Pineapple.",
            "Coconut.",
            "Kiwi.",
            "Kiwifruit.",
            "Tomato.",
            "Eggplant.",
            "Avocado.",
            "Broccoli.",
            "Leafy green.",
            "Cucumber.",
            "Hot pepper.",
            "Corn.",
            "Carrot.",
            "Onion.",
            "Garlic.",
            "Potato.",
            "Sweet potato.",
            "Croissant.",
            "Bagel.",
            "Bread.",
            "French bread.",
            "Baguette bread.",
            "Pretzel.",
            "Cheese.",
            "Cheese wedge.",
            "Egg.",
            "Cooking.",
            "Pancakes.",
            "Waffle.",
            "Bacon.",
            "Cut of meat.",
            "Poultry leg.",
            "Meat on bone.",
            "Hotdog.",
            "Hot dog.",
            "Hamburger.",
            "Fries.",
            "Pizza.",
            "Sandwich.",
            "Falafel.",
            "Stuffed flatbread.",
            "Stuffed pita.",
            "Taco.",
            "Burrito.",
            "Salad.",
            "Green salad.",
            "Shallow pan of food.",
            "Paella.",
            "Canned food.",
            "Spaghetti.",
            "Ramen.",
            "Stew.",
            "Curry.",
            "Sushi.",
            "Bento.",
            "Dumpling.",
            "Fried shrimp.",
            "Rice ball.",
            "Rice.",
            "Rice cracker.",
            "Fish cake.",
            "Fortune cookie.",
            "Moon cake.",
            "Oden.",
            "Dango.",
            "Shaved ice.",
            "Ice cream.",
            "Icecream.",
            "Pie.",
            "Cupcake.",
            "Cake.",
            "Birthday.",
            "Custard.",
            "Pudding.",
            "Flan.",
            "Lollipop.",
            "Candy.",
            "Chocolate bar.",
            "Popcorn.",
            "Doughnut.",
            "Cookie.",
            "Chestnut.",
            "Peanuts.",
            "Shelled peanut.",
            "Honey pot.",
            "Butter.",
            "Milk.",
            "Glass of milk.",
            "Baby bottle.",
            "Coffee.",
            "Tea.",
            "Mate.",
            "Cup with straw.",
            "Beverage box.",
            "Ice cube.",
            "Sake.",
            "Beer.",
            "Beers.",
            "Champagne glass.",
            "Clinking glass.",
            "Wine glass.",
            "Tumbler glass.",
            "Whisky.",
            "Cocktail.",
            "Tropical drink.",
            "Champagne.",
            "Bottle with popping cork.",
            "Spoon.",
            "Fork and knife.",
            "Fork knife plate.",
            "Fork and knife with plate.",
            "Bowl with spoon.",
            "Takeout box.",
            "Chopsticks.",
            "Salt.",
            "Soccer.",
            "Basketball.",
            "Football.",
            "Baseball.",
            "Softball.",
            "Tennis.",
            "Volleyball.",
            "Rugby football.",
            "Flying disc.",
            "8ball.",
            "Ping pong.",
            "Table tennis.",
            "Badminton.",
            "Hockey.",
            "Field hockey.",
            "Lacrosse.",
            "Cricket game.",
            "Cricket bat ball.",
            "Goal.",
            "Goal net.",
            "Golf.",
            "Bow and arrow.",
            "Archery.",
            "Fishing pole and fish.",
            "Boxing glove.",
            "Boxing gloves.",
            "Martial arts uniform.",
            "Karate uniform.",
            "Running shirt with sash.",
            "Skateboard.",
            "Sled.",
            "Parachute.",
            "Ice skate.",
            "Curling stone.",
            "Ski.",
            "Skier.",
            "Snowboarder.",
            "Person lifting weights.",
            "Lifter.",
            "Weight lifter.",
            "Woman lifting weights.",
            "Man lifting weights.",
            "People wrestling.",
            "Wrestlers.",
            "Wrestling.",
            "Women wrestling.",
            "Men wrestling.",
            "Person doing cartwheel.",
            "Cartwheel.",
            "Woman cartwheeling.",
            "Man cartwheeling.",
            "Person bouncing ball.",
            "Basketball player.",
            "Person with ball.",
            "Woman bouncing ball.",
            "Man bouncing ball.",
            "Person fencing.",
            "Fencer.",
            "Fencing.",
            "Person playing handball.",
            "Handball.",
            "Woman playing handball.",
            "Man playing handball.",
            "Person golfing.",
            "Golfer.",
            "Woman golfing.",
            "Man golfing.",
            "Horse racing.",
            "Person in lotus position.",
            "Woman in lotus position.",
            "Man in lotus position.",
            "Person surfing.",
            "Surfer.",
            "Woman surfing.",
            "Man surfing.",
            "Person swimming.",
            "Swimmer.",
            "Woman swimming.",
            "Man swimming.",
            "Person playing water polo.",
            "Water polo.",
            "Woman playing water polo.",
            "Man playing water polo.",
            "Person rowing boat.",
            "Rowboat.",
            "Woman rowing boat.",
            "Man rowing boat.",
            "Person climbing.",
            "Woman climbing.",
            "Man climbing.",
            "Person mountain biking.",
            "Mountain bicyclist.",
            "Woman mountain biking.",
            "Man mountain biking.",
            "Person biking.",
            "Bicyclist.",
            "Woman biking.",
            "Man biking.",
            "Trophy.",
            "First place.",
            "First place medal.",
            "Second place.",
            "Second place medal.",
            "Third place.",
            "Third place medal.",
            "Medal.",
            "Sports medal.",
            "Military medal.",
            "Rosette.",
            "Reminder ribbon.",
            "Ticket.",
            "Tickets.",
            "Admission tickets.",
            "Circus tent.",
            "Person juggling.",
            "Juggling.",
            "Juggler.",
            "Woman juggling.",
            "Man juggling.",
            "Performing arts.",
            "Art.",
            "Clapper.",
            "Microphone.",
            "Headphones.",
            "Musical score.",
            "Musical keyboard.",
            "Drum.",
            "Drum with drumsticks.",
            "Saxophone.",
            "Trumpet.",
            "Banjo.",
            "Guitar.",
            "Violin.",
            "Game die.",
            "Chess pawn.",
            "Dart.",
            "Kite.",
            "Yo yo.",
            "Bowling.",
            "Video game.",
            "Slot machine.",
            "Jigsaw.",
            "Red car.",
            "Taxi.",
            "Blue car.",
            "Bus.",
            "Trolleybus.",
            "Race car.",
            "Racing car.",
            "Police car.",
            "Ambulance.",
            "Fire engine.",
            "Minibus.",
            "Truck.",
            "Articulated lorry.",
            "Tractor.",
            "Auto rickshaw.",
            "Motor scooter.",
            "Motorbike.",
            "Motorcycle.",
            "Racing motorcycle.",
            "Scooter.",
            "Bike.",
            "Motorized wheelchair.",
            "Manual wheelchair.",
            "Rotating light.",
            "Oncoming police car.",
            "Oncoming bus.",
            "Oncoming automobile.",
            "Oncoming taxi.",
            "Aerial tramway.",
            "Mountain cableway.",
            "Suspension railway.",
            "Railway car.",
            "Train.",
            "Mountain railway.",
            "Monorail.",
            "Bullettrain side.",
            "Bullettrain front.",
            "Light rail.",
            "Steam locomotive.",
            "Train2.",
            "Metro.",
            "Tram.",
            "Station.",
            "Airplane.",
            "Airplane departure.",
            "Airplane arriving.",
            "Airplane small.",
            "Small airplane.",
            "Seat.",
            "Satellite orbital.",
            "Rocket.",
            "Flying saucer.",
            "Helicopter.",
            "Canoe.",
            "Kayak.",
            "Sailboat.",
            "Speedboat.",
            "Motorboat.",
            "Cruise ship.",
            "Passenger ship.",
            "Ferry.",
            "Ship.",
            "Anchor.",
            "Fuelpump.",
            "Construction.",
            "Vertical traffic light.",
            "Traffic light.",
            "Busstop.",
            "Map.",
            "World map.",
            "Moyai.",
            "Statue of liberty.",
            "Tokyo tower.",
            "European castle.",
            "Japanese castle.",
            "Stadium.",
            "Ferris wheel.",
            "Roller coaster.",
            "Carousel horse.",
            "Fountain.",
            "Beach umbrella.",
            "Umbrella on ground.",
            "Beach.",
            "Beach with umbrella.",
            "Island.",
            "Desert island.",
            "Desert.",
            "Volcano.",
            "Mountain.",
            "Mountain snow.",
            "Snow capped mountain.",
            "Mount fuji.",
            "Camping.",
            "Tent.",
            "House.",
            "House with garden.",
            "Homes.",
            "House buildings.",
            "House abandoned.",
            "Derelict house building.",
            "Construction site.",
            "Building construction.",
            "Factory.",
            "Office.",
            "Department store.",
            "Post office.",
            "European post office.",
            "Hospital.",
            "Bank.",
            "Hotel.",
            "Convenience store.",
            "School.",
            "Love hotel.",
            "Wedding.",
            "Classical building.",
            "Church.",
            "Mosque.",
            "Hindu temple.",
            "Synagogue.",
            "Kaaba.",
            "Shinto shrine.",
            "Railway track.",
            "Railroad track.",
            "Motorway.",
            "Japan.",
            "Rice scene.",
            "Park.",
            "National park.",
            "Sunrise.",
            "Sunrise over mountains.",
            "Stars.",
            "Sparkler.",
            "Fireworks.",
            "City sunset.",
            "City sunrise.",
            "City dusk.",
            "Cityscape.",
            "Night with stars.",
            "Milky way.",
            "Bridge at night.",
            "Foggy.",
            "Watch.",
            "Iphone.",
            "Calling.",
            "Computer.",
            "Keyboard.",
            "Desktop.",
            "Desktop computer.",
            "Printer.",
            "Mouse three button.",
            "Three button mouse.",
            "Trackball.",
            "Joystick.",
            "Compression.",
            "Minidisc.",
            "Floppy disk.",
            "CD.",
            "DVD.",
            "VHS.",
            "Camera.",
            "Camera with flash.",
            "Video camera.",
            "Movie camera.",
            "Projector.",
            "Film projector.",
            "Film frames.",
            "Telephone receiver.",
            "Telephone.",
            "Pager.",
            "Fax.",
            "TV.",
            "Radio.",
            "Microphone2.",
            "Studio microphone.",
            "Level slider.",
            "Control knobs.",
            "Compass.",
            "Stopwatch.",
            "Timer.",
            "Timer clock.",
            "Alarm clock.",
            "Clock.",
            "Mantlepiece clock.",
            "Hourglass.",
            "Hourglass flowing sand.",
            "Satellite.",
            "Battery.",
            "Electric plug.",
            "Bulb.",
            "Flashlight.",
            "Candle.",
            "Fire extinguisher.",
            "Oil.",
            "Oil drum.",
            "Money with wings.",
            "Dollar.",
            "Yen.",
            "Euro.",
            "Pound.",
            "Moneybag.",
            "Credit card.",
            "Gem.",
            "Scales.",
            "Toolbox.",
            "Wrench.",
            "Hammer.",
            "Hammer pick.",
            "Hammer and pick.",
            "Tools.",
            "Hammer and wrench.",
            "Pick.",
            "Nut and bolt.",
            "Gear.",
            "Bricks.",
            "Chains.",
            "Magnet.",
            "Gun.",
            "Bomb.",
            "Firecracker.",
            "Axe.",
            "Razor.",
            "Knife.",
            "Dagger.",
            "Dagger knife.",
            "Crossed swords.",
            "Shield.",
            "Smoking.",
            "Coffin.",
            "Urn.",
            "Funeral urn.",
            "Amphora.",
            "Diya lamp.",
            "Crystal ball.",
            "Prayer beads.",
            "Nazar amulet.",
            "Barber.",
            "Alembic.",
            "Telescope.",
            "Microscope.",
            "Hole.",
            "Probing cane.",
            "Stethoscope.",
            "Adhesive bandage.",
            "Pill.",
            "Syringe.",
            "Drop of blood.",
            "Dna.",
            "Microbe.",
            "Petri dish.",
            "Test tube.",
            "Thermometer.",
            "Chair.",
            "Broom.",
            "Basket.",
            "Roll of paper.",
            "Toilet.",
            "Potable water.",
            "Shower.",
            "Bathtub.",
            "Bath.",
            "Soap.",
            "Sponge.",
            "Squeeze bottle.",
            "Bellhop.",
            "Bellhop bell.",
            "Key.",
            "Key2.",
            "Old key.",
            "Door.",
            "Couch.",
            "Couch and lamp.",
            "Bed.",
            "Sleeping accommodation.",
            "Teddy bear.",
            "Frame photo.",
            "Frame with picture.",
            "Shopping bags.",
            "Shopping cart.",
            "Shopping trolley.",
            "Gift.",
            "Balloon.",
            "Flag .",
            "Ribbon.",
            "Confetti ball.",
            "Tada.",
            "Dolls.",
            "Izakaya lantern.",
            "Wind chime.",
            "Red envelope.",
            "Envelope.",
            "Envelope with arrow.",
            "Incoming envelope.",
            "E mail.",
            "Email.",
            "Love letter.",
            "Inbox tray.",
            "Outbox tray.",
            "Package.",
            "Label.",
            "Mailbox closed.",
            "Mailbox.",
            "Mailbox with mail.",
            "Mailbox with no mail.",
            "Postbox.",
            "Postal horn.",
            "Scroll.",
            "Page with curl.",
            "Page facing up.",
            "Bookmark tabs.",
            "Receipt.",
            "Bar chart.",
            "Chart with upwards trend.",
            "Chart with downwards trend.",
            "Notepad spiral.",
            "Spiral note pad.",
            "Calendar spiral.",
            "Spiral calendar pad.",
            "Calendar.",
            "Date.",
            "Wastebasket.",
            "Card index.",
            "Card box.",
            "Card file box.",
            "Ballot box.",
            "Ballot box with ballot.",
            "File cabinet.",
            "Clipboard.",
            "File folder.",
            "Open file folder.",
            "Dividers.",
            "Card index dividers.",
            "Newspaper2.",
            "Rolled up newspaper.",
            "Newspaper.",
            "Notebook.",
            "Notebook with decorative cover.",
            "Ledger.",
            "Closed book.",
            "Green book.",
            "Blue book.",
            "Orange book.",
            "Books.",
            "Book.",
            "Bookmark.",
            "Safety pin.",
            "Link.",
            "Paperclip.",
            "Paperclips.",
            "Linked paperclips.",
            "Triangular ruler.",
            "Straight ruler.",
            "Abacus.",
            "Pushpin.",
            "Round pushpin.",
            "Scissors.",
            "Pen ballpoint.",
            "Lower left ballpoint pen.",
            "Pen fountain.",
            "Lower left fountain pen.",
            "Black nib.",
            "Paintbrush.",
            "Lower left paintbrush.",
            "Crayon.",
            "Lower left crayon.",
            "Pencil.",
            "Memo.",
            "Pencil2.",
            "Mag.",
            "Mag right.",
            "Lock with ink pen.",
            "Closed lock with key.",
            "Lock.",
            "Unlock.",
            "Heart.",
            "Orange heart.",
            "Yellow heart.",
            "Green heart.",
            "Blue heart.",
            "Purple heart.",
            "Black heart.",
            "Brown heart.",
            "White heart.",
            "Broken heart.",
            "Heart exclamation.",
            "Heavy heart exclamation mark ornament.",
            "Two hearts.",
            "Revolving hearts.",
            "Heartbeat.",
            "Heartpulse.",
            "Sparkling heart.",
            "Cupid.",
            "Gift heart.",
            "Heart decoration.",
            "Peace.",
            "Peace symbol.",
            "Cross.",
            "Latin cross.",
            "Star and crescent.",
            "Om symbol.",
            "Wheel of dharma.",
            "Star of david.",
            "Six pointed star.",
            "Menorah.",
            "Yin yang.",
            "Orthodox cross.",
            "Place of worship.",
            "Worship symbol.",
            "Ophiuchus.",
            "Aries.",
            "Taurus.",
            "Gemini.",
            "Cancer.",
            "Leo.",
            "Virgo.",
            "Libra.",
            "Scorpius.",
            "Sagittarius.",
            "Capricorn.",
            "Aquarius.",
            "Pisces.",
            "ID.",
            "Atom.",
            "Atom symbol.",
            "Accept.",
            "Radioactive.",
            "Radioactive sign.",
            "Biohazard.",
            "Biohazard sign.",
            "Mobile phone off.",
            "Vibration mode.",
            "U6709.",
            "U7121.",
            "U7533.",
            "U55b6.",
            "U6708.",
            "Eight pointed black star.",
            "VS.",
            "White flower.",
            "Ideograph advantage.",
            "Secret.",
            "Congratulations.",
            "U5408.",
            "U6e80.",
            "U5272.",
            "U7981.",
            "A.",
            "B.",
            "Ab.",
            "Cl.",
            "O2.",
            "SOS.",
            "X.",
            "O.",
            "Octagonal sign.",
            "Stop sign.",
            "No entry.",
            "Name badge.",
            "No entry sign.",
            "100.",
            "Anger.",
            "Hotsprings.",
            "No pedestrians.",
            "Do not litter.",
            "No bicycles.",
            "Non potable water.",
            "Underage.",
            "No mobile phones.",
            "No smoking.",
            "Exclamation.",
            "Grey exclamation.",
            "Question.",
            "Grey question.",
            "Bangbang.",
            "Interrobang.",
            "Low brightness.",
            "High brightness.",
            "Part alternation mark.",
            "Warning.",
            "Children crossing.",
            "Trident.",
            "Fleur de lis.",
            "Beginner.",
            "Recycle.",
            "White check mark.",
            "U6307.",
            "Chart.",
            "Sparkle.",
            "Eight spoked asterisk.",
            "Negative squared cross mark.",
            "Globe with meridians.",
            "Diamond shape with a dot inside.",
            "M.",
            "Cyclone.",
            "Zzz.",
            "ATM.",
            "WC.",
            "Wheelchair.",
            "Parking.",
            "U7a7a.",
            "Sa.",
            "Passport control.",
            "Customs.",
            "Baggage claim.",
            "Left luggage.",
            "Mens.",
            "Womens.",
            "Baby symbol.",
            "Restroom.",
            "Put litter in its place.",
            "Cinema.",
            "Signal strength.",
            "Koko.",
            "Symbols.",
            "Information source.",
            "Abc.",
            "Abcd.",
            "Capital abcd.",
            "NG.",
            "OK.",
            "Up.",
            "Cool.",
            "New.",
            "Free.",
            "Zero.",
            "One.",
            "Two.",
            "Three.",
            "Four.",
            "Five.",
            "Six.",
            "Seven.",
            "Eight.",
            "Nine.",
            "Keycap ten.",
            "1234.",
            "Hash.",
            "Asterisk.",
            "Keycap asterisk.",
            "Eject.",
            "Eject symbol.",
            "Arrow forward.",
            "Pause button.",
            "Double vertical bar.",
            "Play pause.",
            "Stop button.",
            "Record button.",
            "Track next.",
            "Next track.",
            "Track previous.",
            "Previous track.",
            "Fast forward.",
            "Rewind.",
            "Arrow double up.",
            "Arrow double down.",
            "Arrow backward.",
            "Arrow up small.",
            "Arrow down small.",
            "Arrow right.",
            "Arrow left.",
            "Arrow up.",
            "Arrow down.",
            "Arrow upper right.",
            "Arrow lower right.",
            "Arrow lower left.",
            "Arrow upper left.",
            "Arrow up down.",
            "Left right arrow.",
            "Arrow right hook.",
            "Leftwards arrow with hook.",
            "Arrow heading up.",
            "Arrow heading down.",
            "Twisted rightwards arrows.",
            "Repeat.",
            "Repeat one.",
            "Arrows counterclockwise.",
            "Arrows clockwise.",
            "Musical note.",
            "Notes.",
            "Heavy plus sign.",
            "Heavy minus sign.",
            "Heavy division sign.",
            "Heavy multiplication x.",
            "Infinity.",
            "Heavy dollar sign.",
            "Currency exchange.",
            "TM.",
            "Copyright.",
            "Registered.",
            "Wavy dash.",
            "Curly loop.",
            "Loop.",
            "End.",
            "Back.",
            "On.",
            "Top.",
            "Soon.",
            "Heavy check mark.",
            "Ballot box with check.",
            "Radio button.",
            "White circle.",
            "Black circle.",
            "Red circle.",
            "Blue circle.",
            "Brown circle.",
            "Purple circle.",
            "Green circle.",
            "Yellow circle.",
            "Orange circle.",
            "Small red triangle.",
            "Small red triangle down.",
            "Small orange diamond.",
            "Small blue diamond.",
            "Large orange diamond.",
            "Large blue diamond.",
            "White square button.",
            "Black square button.",
            "Black small square.",
            "White small square.",
            "Black medium small square.",
            "White medium small square.",
            "Black medium square.",
            "White medium square.",
            "Black large square.",
            "White large square.",
            "Orange square.",
            "Blue square.",
            "Red square.",
            "Brown square.",
            "Purple square.",
            "Green square.",
            "Yellow square.",
            "Speaker.",
            "Mute.",
            "Sound.",
            "Loud sound.",
            "Bell.",
            "No bell.",
            "Mega.",
            "Loudspeaker.",
            "Speech left.",
            "Left speech bubble.",
            "Eye in speech bubble.",
            "Speech balloon.",
            "Thought balloon.",
            "Anger right.",
            "Right anger bubble.",
            "Spades.",
            "Clubs.",
            "Hearts.",
            "Diamonds.",
            "Black joker.",
            "Flower playing cards.",
            "Mahjong.",
            "Clock1.",
            "Clock2.",
            "Clock3.",
            "Clock4.",
            "Clock5.",
            "Clock6.",
            "Clock7.",
            "Clock8.",
            "Clock9.",
            "Clock10.",
            "Clock11.",
            "Clock12.",
            "Clock130.",
            "Clock230.",
            "Clock330.",
            "Clock430.",
            "Clock530.",
            "Clock630.",
            "Clock730.",
            "Clock830.",
            "Clock930.",
            "Clock1030.",
            "Clock1130.",
            "Clock1230.",
            "Female sign.",
            "Male sign.",
            "Medical symbol.",
            "Regional indicator z.",
            "Regional indicator y.",
            "Regional indicator x.",
            "Regional indicator w.",
            "Regional indicator v.",
            "Regional indicator u.",
            "Regional indicator t.",
            "Regional indicator s.",
            "Regional indicator r.",
            "Regional indicator q.",
            "Regional indicator p.",
            "Regional indicator o.",
            "Regional indicator n.",
            "Regional indicator m.",
            "Regional indicator l.",
            "Regional indicator k.",
            "Regional indicator j.",
            "Regional indicator i.",
            "Regional indicator h.",
            "Regional indicator g.",
            "Regional indicator f.",
            "Regional indicator e.",
            "Regional indicator d.",
            "Regional indicator c.",
            "Regional indicator b.",
            "Regional indicator a.",
            "Flag white.",
            "Flag black.",
            "Checkered flag.",
            "Triangular flag on post.",
            "Rainbow flag.",
            "Gay pride flag.",
            "Pirate flag.",
            "Flag AF.",
            "Flag AX.",
            "Flag AL.",
            "Flag DZ.",
            "Flag AS.",
            "Flag AD.",
            "Flag AO.",
            "Flag AI.",
            "Flag AQ.",
            "Flag AG.",
            "Flag AR.",
            "Flag AM.",
            "Flag AW.",
            "Flag AU.",
            "Flag AT.",
            "Flag AZ.",
            "Flag BS.",
            "Flag BH.",
            "Flag BD.",
            "Flag BB.",
            "Flag BY.",
            "Flag BE.",
            "Flag BZ.",
            "Flag BJ.",
            "Flag BM.",
            "Flag BT.",
            "Flag BO.",
            "Flag BA.",
            "Flag BW.",
            "Flag BR.",
            "Flag IO.",
            "Flag VG.",
            "Flag BN.",
            "Flag BG.",
            "Flag BF.",
            "Flag BI.",
            "Flag KH.",
            "Flag CM.",
            "Flag CA.",
            "Flag IC.",
            "Flag CV.",
            "Flag BQ.",
            "Flag KY.",
            "Flag CF.",
            "Flag TD.",
            "Flag CL.",
            "Flag CN.",
            "Flag CX.",
            "Flag CC.",
            "Flag CO.",
            "Flag KM.",
            "Flag CG.",
            "Flag CD.",
            "Flag CK.",
            "Flag CR.",
            "Flag CI.",
            "Flag HR.",
            "Flag CU.",
            "Flag CW.",
            "Flag CY.",
            "Flag CZ.",
            "Flag DK.",
            "Flag DJ.",
            "Flag DM.",
            "Flag DO.",
            "Flag EC.",
            "Flag EG.",
            "Flag SV.",
            "Flag GQ.",
            "Flag ER.",
            "Flag EE.",
            "Flag ET.",
            "Flag EU.",
            "Flag FK.",
            "Flag FO.",
            "Flag FJ.",
            "Flag FI.",
            "Flag FR.",
            "Flag GF.",
            "Flag PF.",
            "Flag TF.",
            "Flag GA.",
            "Flag GM.",
            "Flag GE.",
            "Flag DE.",
            "Flag GH.",
            "Flag GI.",
            "Flag GR.",
            "Flag GL.",
            "Flag GD.",
            "Flag GP.",
            "Flag GU.",
            "Flag GT.",
            "Flag GG.",
            "Flag GN.",
            "Flag GW.",
            "Flag GY.",
            "Flag HT.",
            "Flag HN.",
            "Flag HK.",
            "Flag HU.",
            "Flag IS.",
            "Flag IN.",
            "Flag ID.",
            "Flag IR.",
            "Flag IQ.",
            "Flag IE.",
            "Flag IM.",
            "Flag IL.",
            "Flag IT.",
            "Flag JM.",
            "Flag JP.",
            "Crossed flags.",
            "Flag JE.",
            "Flag JO.",
            "Flag KZ.",
            "Flag KE.",
            "Flag KI.",
            "Flag XK.",
            "Flag KW.",
            "Flag KG.",
            "Flag LA.",
            "Flag LV.",
            "Flag LB.",
            "Flag LS.",
            "Flag LR.",
            "Flag LY.",
            "Flag LI.",
            "Flag LT.",
            "Flag LU.",
            "Flag MO.",
            "Flag MK.",
            "Flag MG.",
            "Flag MW.",
            "Flag MY.",
            "Flag MV.",
            "Flag ML.",
            "Flag MT.",
            "Flag MH.",
            "Flag MQ.",
            "Flag MR.",
            "Flag MU.",
            "Flag YT.",
            "Flag MX.",
            "Flag FM.",
            "Flag MD.",
            "Flag MC.",
            "Flag MN.",
            "Flag ME.",
            "Flag MS.",
            "Flag MA.",
            "Flag MZ.",
            "Flag MM.",
            "Flag NA.",
            "Flag NR.",
            "Flag NP.",
            "Flag NL.",
            "Flag NC.",
            "Flag NZ.",
            "Flag NI.",
            "Flag NE.",
            "Flag NG.",
            "Flag NU.",
            "Flag NF.",
            "Flag KP.",
            "Flag MP.",
            "Flag NO.",
            "Flag OM.",
            "Flag PK.",
            "Flag PW.",
            "Flag PS.",
            "Flag PA.",
            "Flag PG.",
            "Flag PY.",
            "Flag PE.",
            "Flag PH.",
            "Flag PN.",
            "Flag PL.",
            "Flag PT.",
            "Flag PR.",
            "Flag QA.",
            "Flag RE.",
            "Flag RO.",
            "Flag RU.",
            "Flag RW.",
            "Flag WS.",
            "Flag SM.",
            "Flag ST.",
            "Flag SA.",
            "Flag SN.",
            "Flag RS.",
            "Flag SC.",
            "Flag SL.",
            "Flag SG.",
            "Flag SX.",
            "Flag SK.",
            "Flag SI.",
            "Flag GS.",
            "Flag SB.",
            "Flag SO.",
            "Flag ZA.",
            "Flag KR.",
            "Flag SS.",
            "Flag ES.",
            "Flag LK.",
            "Flag BL.",
            "Flag SH.",
            "Flag KN.",
            "Flag LC.",
            "Flag PM.",
            "Flag VC.",
            "Flag SD.",
            "Flag SR.",
            "Flag SZ.",
            "Flag SE.",
            "Flag CH.",
            "Flag SY.",
            "Flag TW.",
            "Flag TJ.",
            "Flag TZ.",
            "Flag TH.",
            "Flag TL.",
            "Flag TG.",
            "Flag TK.",
            "Flag TO.",
            "Flag TT.",
            "Flag TN.",
            "Flag TR.",
            "Flag TM.",
            "Flag TC.",
            "Flag VI.",
            "Flag TV.",
            "Flag UG.",
            "Flag UA.",
            "Flag AE.",
            "Flag GB.",
            "England.",
            "Scotland.",
            "Wales.",
            "Flag US.",
            "Flag UY.",
            "Flag UZ.",
            "Flag VU.",
            "Flag VA.",
            "Flag VE.",
            "Flag VN.",
            "Flag WF.",
            "Flag EH.",
            "Flag YE.",
            "Flag ZM.",
            "Flag ZW.",
            "Flag AC.",
            "Flag BV.",
            "Flag CP.",
            "Flag EA.",
            "Flag DG.",
            "Flag HM.",
            "Flag MF.",
            "Flag SJ.",
            "Flag TA.",
            "Flag UM.",
            "United nations.",

            // Misc
            "Code?",
            "LMAO!",
        };

        private static readonly Dictionary<ulong, ChatChannel> Channels = new Dictionary<ulong, ChatChannel>();

        private static int GetChatRepeats(ulong id, string chat)
        {
            if (!Channels.TryGetValue(id, out var channel))
            {
                Channels[id] = channel = new ChatChannel();
            }

            if (chat != channel.LastSent)
            {
                channel.RepeatCount = 0;
                channel.LastSent = chat;
            }

            return ++channel.RepeatCount;
        }

        private class ChatChannel
        {
            public string LastSent;
            public int RepeatCount;
            public int DelayCount;
        }


        public static void Bind(DiscordSocketClient client)
        {
            client.MessageReceived += Client_MessageReceived;
            client.MessageUpdated += Client_MessageUpdated;
        }

        private static async Task Client_MessageUpdated(Discord.Cacheable<Discord.IMessage, ulong> arg1, SocketMessage msg, ISocketMessageChannel arg3)
        {
            if (msg.Channel.Name == "quickchat")
            {
                await msg.DeleteAsync();
            }
        }

        private static async Task Client_MessageReceived(SocketMessage msg)
        {
            if (msg.Author.IsBot) return;
            if (msg.Channel.Name == "quickchat")
            {
                var repeats = GetChatRepeats(msg.Author.Id, msg.Content);
                if (repeats == 3)
                {
                    await msg.Channel.SendMessageAsync("Easy now, you don't want the other players mistaking you for a spammer!");
                }
                if (repeats >= 3 || !IsValidContent(msg))
                {
                    await msg.DeleteAsync();
                }
            }
        }

        private static bool IsValidContent(SocketMessage msg)
        {
            if (ValidQuickChats.Contains(msg.Content)) return true;
            if (MentionUtils.TryParseUser(msg.Content, out var userId))
            {
                if (msg.Channel.GetUserAsync(userId, CacheMode.CacheOnly).Result != null) return true;
            }
            if (msg.Content.StartsWith("<:chat:329704537050841091> ||") && msg.Content.EndsWith("||") && !msg.Content.EndsWith("\\||"))
            {
                _ = Task.Delay(30000).ContinueWith((a) => msg.DeleteAsync());
                return true;
            }
            return false;
        }
    }
}
